### ISSUE TITLE
Difference from https://github.com/apache/thrift/blob/master/lib/nodejs/lib/thrift/browser.js   ??

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [vh/browser-thrift#3]
Hi, 

Thank you for your webpack ready thrift library.

There is [browser.js file](https://github.com/apache/thrift/blob/master/lib/nodejs/lib/thrift/browser.js)  for browser use. 

Is there any functional difference?

**Comment by vh** [comment]
Hi!
As I remember, I had been facing some issues when tried to use browser.js with webpack. You can check that browser.js and https://github.com/vh/browser-thrift/blob/master/src/index.js are very similar.
Anyway I've made some changes for transport exception handling like Timeout, Not opened etc.
 
You are welcome!

**Comment by HIRANO-Satoshi** [comment]
@vh Thank you for quick reply. 

Are you using Thrift with your browser-thrift for production? Does binary protocol work for you?

I also made my own index.js for browser use. Since the binary protocol did not work, I'm using JSON protocol which is slow.

Yesterday I tried the browser.js. I found it is non sense because generated files by thrift compiler included require('thrift').  :-)

**Comment by vh** [comment]
Yes, for production and I'm using compact protocol. I've made some fixes for binary/compact protocol support you can check - https://github.com/vh/browser-thrift/commit/c3f0969e9875190924dba18d15c11f1b3c973730 
Regarding browser.js you are right - generated files require 'thrift' :)

**Comment by HIRANO-Satoshi** [comment]
Thanks. I looked at your modification.  Do you have a plan to make a PR for the Thrift project?

Thrift packages on the npm repository lack dependency in package.json. I need to do npm install modules such as node-int64, net, tls and so on by hand.

**Comment by vh** [comment]
At this moment not. I did some but it is still not merged. They also merged error handling based on event loop. I don't really like such approach.
