### ISSUE TITLE
Help on using this library

### ISSUE THREAD

**Issue by emmenlau** [vh/browser-thrift#6]
Could you add more details how this library should be used? I could browserify the sources into `browser-thrift.js` and try to use that in the browser instead of `thrift.js` but it does not work. All I get are errors from my gen-js files that `Thrift` is not defined.

**Comment by vh** [comment]
Did you replace `thrift` with `browser-thrift` in generated files?

**Comment by emmenlau** [comment]
I did, I called `sed` for the replace, but I think that `require('thrift')` was not there before? Should the generated files be nodejs or js?

Here are the steps I did (in pseudo-code), are they correct?
  * `browserify src/index.js -o browser-thrift.js`
  * copy `browser-thrift.js` next to `index.html`
  * `thrift -strict -recurse -o ./ -gen js tutorial.thrift`

And in `index.html` I have:
```
    <script src="browser-thrift.js"></script>
    <script src="gen-js/tutorial_types.js"></script>
    <script src="gen-js/tutorial.js"></script>

    <script>
        var transport = new Thrift.Transport("http://localhost:9090/thrift/service/tutorial/");
        var protocol = new Thrift.TJSONProtocol(transport);
        var client = new ThriftWebServiceAPIClient(protocol);
        var vResult = client.ping(12345);
    </script>
```
But this gives errors `Thrift undefined`.

Could you add an example with html and thrift file that works? Then everything may be much simpler.

**Comment by vh** [comment]
Generated files should be node.js files (`js:node`) and then you should `require(...)` them.

**Comment by emmenlau** [comment]
Thanks! But then, I need to browserify the generated files? Otherwise, how is `require(...)` resolved in the browser?

**Comment by vh** [comment]
Sure. I personally never used it with browserify (only webpack) but there are no reason why it should't work. Let me know if that works!

**Comment by emmenlau** [comment]
Ok, I just could not get it to work, which is most likely because I'm not knowledgeable with browserify or webpack :-(

However I managed to get the official thrift nodejs implementation to work in the browser with webpack. I'll try to get my documentation integrated with the upstream repository. But in the meantime I'm also linking this here in case more people are interested: https://github.com/BioDataAnalysis/thrift-nodejs-browser
